GritsConstants = {}
# session keys
GritsConstants.SESSION_KEY_MODE = 'grits-net-meteor:mode'
GritsConstants.SESSION_KEY_IS_UPDATING = 'grits-net-meteor:isUpdating'
GritsConstants.SESSION_KEY_IS_READY = 'grits-net-meteor:isReady'
GritsConstants.SESSION_KEY_TOTAL_RECORDS = 'grits-net-meteor:totalRecords'
GritsConstants.SESSION_KEY_LOADED_RECORDS = 'grits-net-meteor:loadedRecords'
GritsConstants.SESSION_KEY_SHARED_SIMID = 'grits-net-meteor:simId'
# map modes
GritsConstants.MODE_EXPLORE = 'EXPLORE'
GritsConstants.MODE_ANALYZE = 'ANALYZE'
# group layer ids
GritsConstants.EXPLORE_GROUP_LAYER_ID = 'explore'
GritsConstants.ANALYZE_GROUP_LAYER_ID = 'analyze'
GritsConstants.HEATMAP_GROUP_LAYER_ID = 'heatmap'
GritsConstants.ALL_NODES_GROUP_LAYER_ID = 'all_nodes'
# sub-layer ids
GritsConstants.NODE_LAYER_ID = 'nodes'
GritsConstants.PATH_LAYER_ID = 'paths'
GritsConstants.HEATMAP_LAYER_ID = 'heatmap'
